# golangci-lint configuration

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose

  disable:
    - depguard

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable:
      - shadow

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/scmd/scmd

  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose

    # Exclude some linters from running on test utilities
    - path: tests/
      linters:
        - errcheck

  max-issues-per-linter: 50
  max-same-issues: 10
